# cc_binary(
#     name = "array_using_template",
#     srcs = [
#         "array_using_template.cpp",
#         "main.cpp",
#         "array_using_template.hpp",
#     ],
# )

cc_binary(
    name = "array_using_template",
    srcs = ["main.cpp"],
)
# cc_import(
#   name = "mylib",
#   hdrs = ["mylib.h"],
#   static_library = "libmylib.a",
#   # If alwayslink is turned on,
#   # libmylib.a will be forcely linked into any binary that depends on it.
#   # alwayslink = 1,
# )

# cc_binary(
#     name = "array",
#     srcs = ["main.cpp"],
#     deps = [":array_using_template"],
# )
